version: 0.1
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y apt-transport-https curl
      - sh scripts/install_yarn.sh
      - sh scripts/install_terraform.sh
  pre_build:
    commands:
      - yarn --frozen-lockfile
      - sh scripts/init_terraform.sh
  build:
    commands:
      - cd infra && terraform plan && cd ../
      - yarn migrate
      - yarn deploy
