version: 0.1
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y apt-transport-https curl
      - sh scripts/install_yarn.sh
      - sh scripts/install_terraform.sh
      - bash scripts/install_gitcrypt.sh
  pre_build:
    commands:
      - bash scripts/decrypt.sh
      - bash scripts/install_dependencies.sh
      - bash scripts/init_terraform.sh
  build:
    commands:
      - bash scripts/apply_terraform.sh
      - bash scripts/deploy_sls.sh
