service:
  name: pressbutton

# Add the serverless-webpack plugin
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: false

custom:
  webpack:
    includeModules:
      forceInclude:
        - pg
    packager: 'yarn'      # Defaults to npm

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  vpc:
    securityGroupIds:
      - ${file(../infra/outputs.json):lambda_security_group.value}
    subnetIds: ${file(../infra/outputs.json):public_subnet_ids.value}

functions:
  migrate:
    handler: src/handlers/migrate.handler
    timeout: 60
    environment:
      DB_HOST: ${env:DB_HOST, file(../infra/outputs.json):rds_host.value}
      DB_USER: ${env:DB_USER, file(../infra/outputs.json):rds_user.value}
      DB_PASS: ${env:DB_PASS, file(../secrets/dev.json):db_pass}
      DB_NAME: "${env:DB_NAME, 'pressbutton'}"
      DB_PORT: "${env:DB_PORT, '5432'}"
  trigger:
    handler: src/handlers/trigger.handler
    timeout: 30
    environment:
      DB_HOST: ${env:DB_HOST, file(../infra/outputs.json):rds_host.value}
      DB_USER: ${env:DB_USER, file(../infra/outputs.json):rds_user.value}
      DB_PASS: ${env:DB_PASS, file(../secrets/dev.json):db_pass}
      DB_NAME: "${env:DB_NAME, 'pressbutton'}"
      DB_PORT: "${env:DB_PORT, '5432'}"
    events:
      - http:
          method: POST
          path: trigger
      - http:
          method: GET
          path: trigger

