steps:
  - label: ":lock: decrypt secrets"
    command: bash scripts/decrypt.sh
  - label: "install dependencies"
    command: bash scripts/install_dependencies.sh
  - wait:
  - label: "apply terraform"
    command: bash scripts/apply_terraform.sh
    concurrency: 1
    artifact_paths:
      - "infra/outputs.json"
      - "infra/terraform.tfstate"

