steps:
  - label: ":lock: decrypt secrets"
    command: bash scripts/decrypt.sh
  - label: "install dependencies"
    command: bash scripts/install_dependencies.sh
  - label: "init terraform"
    command: bash scripts/init_terraform.sh
  - wait:

