steps:
  - id: "lint"
    label: "lint"
    commands:
      - bash scripts/runin.sh backend yarn install
      - bash scripts/runin.sh backend yarn lint
  - id: "compile"
    label: "compile"
    commands:
      - bash scripts/runin.sh backend yarn install
      - bash scripts/runin.sh backend yarn compile
  - block: ":rocket: release to dev"
  - id: "terraform"
    label: "apply terraform"
    commands:
      - bash scripts/decrypt.sh
      - bash scripts/apply_terraform.sh
    concurrency: 1
    concurrency_group: "terraform"
    artifact_paths:
      - "infra/outputs.json"
      - "infra/terraform.tfstate"
  - wait:
  - id: "migrate"
    label: ":rocket: migrate to sls"
    commands:
      - buildkite-agent artifact download 'infra/outputs.json' infra/ --step 'apply terraform'
      - bash scripts/decrypt.sh
      - bash scripts/migrate.sh
    concurrency: 1
    concurrency_group: "migrate"
  - wait:
  - id: "deploy"
    label: ":rocket: deploy to sls"
    commands:
      - buildkite-agent artifact download 'infra/outputs.json' infra/ --step 'apply terraform'
      - bash scripts/decrypt.sh
      - bash scripts/deploy_sls.sh
    concurrency: 1
    concurrency_group: "deploy"
    artifact_paths:
      - "backend/.serverless/**/*"
