steps:
  - id: "terraform"
    label: "apply terraform"
    commands:
      - bash scripts/decrypt.sh
      - bash scripts/apply_terraform.sh
    concurrency: 1
    concurrency_group: "terraform"
    artifact_paths:
      - "infra/outputs.json"
      - "infra/terraform.tfstate"
  - wait:
  - id: "deploy"
    label: ":rocket: deploy to sls"
    commands:
      - buildkite-agent artifact download 'infra/outputs.json' infra/ --step terraform
      - bash scripts/decrypt.sh
      - bash scripts/deploy_sls.sh
    concurrency: 1
    concurrency_group: "deploy"
    artifact_paths:
      - "backend/.serverless/**/*"
